### ISSUE TITLE
Race condition between `subscribe` and `stream` leading to duplicated records

### ISSUE THREAD

**Issue by backuitist** [ovotech/fs2-kafka#105]
When subscribing to a topic the `KafkaConsumerActor` adds a rebalancing hook that registers `FetchRequest`s.
Then when calling `stream` the `KafkaConsumer` will requests partition assignments and - that's the race condition - depending on the timing might get some partition ids for which it will also register `FetchRequest`s.
This is aggravated by the fact that the `KafkaConsumerActor.State` does not restrict the amount of `FetchRequest`s per (partition, consumer), leading to duplicated records sent downstream.

**Comment by vlovgr** [comment]
Thanks for finding and reporting this @backuitist! I found another related issue, and opened #106 to address this. Would you mind having a look?
