### ISSUE TITLE
Should commit batch functions sort offsets?

### ISSUE THREAD

**Issue by javierarrieta** [ovotech/fs2-kafka#137]
This is more a question than an issue, as it might work as intended. We are experiences some difficulties when doing grouping per key and then trying to commit the offsets, as when collecting the offsets they are potentially out of order and the commit functions will commit the last offset of the `TopicPartition` and not the one most forward.

We might sort them out again but that would be quite costly as the commit batch functions are folding on the `CommittableOffsets`.

Is this behaviour a design decision? What would be a good pattern to work this way if it is? (I was experimenting with a container that will have the entities being transformed and the batch of committable offsets but it was getting a bit unwieldy when doing `mapAsync`

I would be happy to work on a fix if it is the best course of action. 

This is the code I was working with:

```scala

import cats.effect._
import cats.syntax.all._
import cats.instances.list._
import fs2.kafka._
import fs2._

import scala.concurrent.duration._
import scala.collection.immutable.List

object GroupedTopicReaderApp extends IOApp {
  override def run(args: List[String]): IO[ExitCode] = {
    val consumerSettings =
      ConsumerSettings[String, String]
        .withAutoOffsetReset(AutoOffsetReset.Earliest)
        .withBootstrapServers("localhost:9092")
        .withGroupId("grouped-reader")
          .withAutoCommitInterval(Integer.MAX_VALUE.nanos)

    consumerStream[IO].using(consumerSettings)
      .evalTap(_.subscribeTo("test"))
      .flatMap(processAndCommit)
      .compile.drain *> IO.pure(ExitCode.Success)
  }

  private val processGroupedMsgs: ((String, List[CommittableMessage[IO, String, String]])) => IO[List[CommittableMessage[IO, String, String]]] =
  { case (_, messages) =>
    IO.delay(println(s"Message count: ${messages.size}")) *>
        messages.map(msg => IO(println(s"${msg.record.key} -> ${msg.record.value}"))).sequence  *>
          IO.pure(messages)
  }

  private def commitMsgs: Chunk[CommittableMessage[IO, String, String]] => Stream[IO, Unit] = { chunk =>
    Stream.chunk(chunk.map(_.committableOffset)).covary[IO].map(IO.pure).through(commitBatchF)
  }

  private val processAndCommit: KafkaConsumer[IO, String, String] => Stream[IO, Unit] = { consumer =>
    consumer.stream.chunks
      .flatMap(c => Stream(c.toList.groupBy(_.record.key).to[List]: _*))
      .mapAsync(1)(processGroupedMsgs)
      .chunks.map(_.flatMap(l => Chunk(l: _*))).flatMap(commitMsgs)
  }
}
```

**Comment by javierarrieta** [comment]
Well, I did more testing (I am not that familiar with fs2) and looks like there is a problem with my assumptions as the chunks are being re-chunked I guess when doing the `mapAsync`, so that processing model won't ever work

**Comment by vlovgr** [comment]
Hi @javierarrieta! In order to ensure at-least-once delivery, we cannot change the order of records or offsets as we process them. This is a general constraint, and sorting will not help here. The situation we want is that: for any committed offset `n`, all records before `n` have been processed. In your example, the `groupBy` operation changes the order of the offsets, meaning there is a possibility we commit an offset even though we haven't processed all previous offsets.

If you want to process a `Chunk` and commit the offsets, you can do something like the following.

```scala
consumer
  .stream
  .chunks
  .evalMap { chunk => 
    val batch = CommittableOffsetBatch.fromFoldableMap(chunk)(_.committableOffset)
    val records = chunk.toList.groupBy(_.record.key).to[List]
    records.traverse(processMessage) >> batch.commit
  }
```

**Comment by javierarrieta** [comment]
Thanks @vlovgr for the quick response, I will experiment with that, I have something similar using a container.
