### ISSUE TITLE
How to make infinite retry

### ISSUE THREAD

**Issue by BBartosz** [ovotech/fs2-kafka#155]
Maybe im lacking some fs2 knowledge, but im interested in scenario where I could infinitely keep polling from kafka and repeat the message processing. Cant find this scenario in docs and I bet its dead simple but apparently im missing something.

**Comment by vlovgr** [comment]
Looks like you got the help you needed in the fs2 Gitter channel. :)

Closing this, but feel free to reopen or visit the fs2-kafka Gitter channel.

**Comment by BBartosz** [comment]
Yeap I got it, so not to loose the response I will write it here. Maybe somebody will search for "infinite retry" in this repo and will find this issue. Long story short thats the solution:
```scala
val consumer = consumerStream[F]
        .using(mySettings)
        .evalTap(_.subscribeTo(myTopic))(concurrentEffect)
        .flatMap(_.stream)


      val consumerStream: fs2.Stream[F, CommittableMessage[F, String, Array[Byte]]] = consumer.mapAsync(1) { message =>
          messageService.process(message).map {
            case Right(_) => message
            case Left(e: MyException) => throw e

        }
      }

      def repeated: fs2.Stream[F, CommittableMessage[F, String, Array[Byte]]] = s.handleErrorWith(_ => repeated)
repeated.map(_.committableOffset.pure[F])
        .through(commitBatchWithinF(1, 2.seconds))
        .as(ExitCode.Success)
```
@vlovgr could you review?

**Comment by vlovgr** [comment]
Both alternatives will close and restart the consumer on errors. The difference is whether you want errors from the `mapAsync` stage, or the commit, to also result in a restart. I would recommend defining your entire stream and place the `handleErrorWith` at the very end, to restart regardless of which stage failed.

**Comment by BBartosz** [comment]
Lets say if i have error when commiting offset to kafka that means something is really wrong so stop my application immediately. When something happened in my processing part then I want retry. So if i would like to avoid restarting whole consumer, does it sounds like a proper solution:

```scala
val s: fs2.Stream[F, CommittableMessage[F, String, Array[Byte]]] = consumer.mapAsync(1) { message =>
        def repeatedF: F[CommittableMessage[F, String, Array[Byte]]] = messageService.process(message).map {
          case Right(msg) => message
          case Left(e: MyException) => {
            throw e
          }
        }.handleErrorWith(_ => repeatedF)
        repeatedF
      }
```

**Comment by vlovgr** [comment]
Yes, that will only retry the message processing, without restarting the consumer on processing errors.

As a side note, you should avoid `throw` in `map`, and can use `rethrow` instead.

```scala
messageService.process(message).rethrow
```

**Comment by BBartosz** [comment]
Some clarification:
```scala
messageService.process(message)
```
Returns `F[Either[SomeException, KafkaMessage]]` so i cant do rethrow. Thats possible solution?

```scala
def repeatedF2: fs2.Stream[F, CommittableMessage[F, String, Array[Byte]]] =
          fs2.Stream.eval(messageService.process(message)).rethrow.handleErrorWith(_ => repeatedF2)
        repeatedF2
```

**Comment by vlovgr** [comment]
It's going a bit off the issue, but `rethrow` only works on `F[Either[Throwable, A]]`.

You can also do it manually if changing the return type of `process` is not an option.

```scala
messageService.process(message)
  .flatMap(_.fold(F.raiseError, F.pure))
```

**Comment by BBartosz** [comment]
Ok got it, thank you for help.
