### ISSUE TITLE
Dependency Issue

### ISSUE THREAD

**Issue by justinhj** [ovotech/fs2-kafka#159]
Using Java 2.12.8 I'm unable to build the latest milestone release. Looks like maybe the kafka-avro-serializer is no longer available, and needs to be bumped to 5.3.0?

[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	::          UNRESOLVED DEPENDENCIES         ::
[warn] 	::::::::::::::::::::::::::::::::::::::::::::::
[warn] 	:: io.confluent#kafka-avro-serializer;5.2.2: not found

[warn] 	Note: Unresolved dependencies path:
[warn] 		io.confluent:kafka-avro-serializer:5.2.2
[warn] 		  +- com.ovoenergy:fs2-kafka-vulcan_2.12:0.20.0-M2

**Comment by vlovgr** [comment]
You need to add the Confluent resolver to your `build.sbt`.

```scala
resolvers += "confluent" at "https://packages.confluent.io/maven/"
```

This should be in the getting started documentation, will update.

**Comment by justinhj** [comment]
That got it! Thanks for your time.

**Comment by vlovgr** [comment]
https://github.com/ovotech/fs2-kafka/pull/161 has been merged and published to clarify this.
