### ISSUE TITLE
Transactions over multiple topics with messages of different types

### ISSUE THREAD

**Issue by shn-amn** [ovotech/fs2-kafka#183]
Hey guys,

Imagine a use case where a service consumes a message with data `a: A` from topic `aTopic` and is supposed to processes it to obtain data `b: B` and `c: C`, open a transaction, write `b` to `bTopic` and `c` to `cTopic`, commit consumption of `a`'s offset, and commit and close the transaction.

A `TransactionalKafkaProducer[F, K, V]` can `.produce` `TransactionalProducerRecords[F, G, K, V, P]` and optionally commit messages from which these records are originated, which is very convenient. But this does not seem to solve the problem at hand.

Is there a different means of doing that in FS2 Kafka? 
If there isn't, do you plan to add this functionality?
If you don't, would you be interested in a pull request on the subject?

Thanks!

**Comment by vlovgr** [comment]
This is supported in `TransactionalProducerRecords`, which contains `Chunk[CommittableProducerRecords]`, which contains a `Chunk[ProducerRecord]`. Each `ProducerRecord` is for a specific topic, so you can produce to multiple topics within the same transaction (even for a single offset).

(There's on-going work on transactions, which hopefully simplifies this a bit.)

**Comment by shn-amn** [comment]
Right. I understand that you can produce multiple messages to multiple topics. But as I understand it, the types `K` and `V` of `TransactionalProducerRecords[_, _, K, V, _]` are the same as those of `CommittableProducerRecords[_, _, K, V]` and `ProducerRecord[K, V]`. So, I suppose all produced records are to be of the same type `V`. Whereas I'm producing messages of different types, `B` ≠ `C` in the example above.

(Now, I can always serialize my messages before hand and have the same type of byte array or something for `V`, but then I lose all the convenience of using Vulcan for example. So that's not what I want to do.)

Am I being wrong somewhere?

**Comment by vlovgr** [comment]
> So, I suppose all produced records are to be of the same type `V`.

Note `V` can be a coproduct (e.g. `sealed trait` + `case class`es, or Shapeless `Coproduct`) and you can define a `Serializer` which then has access to both the coproduct value, as well as the headers and topic name during serialization, and can choose to serialize them differently.
