### ISSUE TITLE
isomorphism between fs2-ConsumerRecord and kafka raw ConsumerRecord

### ISSUE THREAD

**Issue by chenharryhua** [ovotech/fs2-kafka#197]
I try to establish an isomorphism between fs2's ConsumerRecord and the kafka raw ConsumerRecord: https://github.com/chenharryhua/nanjin/blob/master/codec/src/main/scala/com/github/chenharryhua/nanjin/codec/BitraverseFs2Message.scala#L53

the problem here is the the implementation of fs2 ConsumerRecords' TimestampType does not carry the timestamp information when it is `none`. 

My understanding is that the timestamp-type is not related to timestamp so that they might setup independently.
Am I missing something?

**Comment by vlovgr** [comment]
My understanding is `timestamp == null` implies `timestampType == NO_TIMESTAMP_TYPE` and vice versa. Unfortunately, this is not enforced in the Java API, so it's entirely possible to create `ConsumerRecord`  instances without this constraint. 

What does it mean for `timestamp != null`  when `timestampType == NO_TIMESTAMP_TYPE`? I'm happy to have it changed if it's a valid variant.

**Comment by chenharryhua** [comment]
given the description: https://github.com/apache/kafka/blob/trunk/clients/src/main/java/org/apache/kafka/clients/consumer/ConsumerRecord.java#L52
I thought that NO_TIMESTAMP and NO_TIMESTAMP_TYPE was introduced to make the client api to be compatible to pre-0.9 kafka brokers. 
also given the doc: https://kafka.apache.org/22/documentation.html (search for log.message.timestamp.type). on broker side, they use one bit to represent Timestamp_Type which is either (0: create time) or (1: log append time). 
so my conclusion is that:
1. when broker is pre-0.9, the timestamp and timestamp type will be both -1
2. when broker is post-0.9, the timestamp and timestamp type are retrieved from brokers.
I think fs2.kafka is implemented properly according to that.
But, if I want to use fs2.kafka to generate improper ConsumerRecord which has wrong combination of timestamp and timestamp_type (timestamp != -1 and timestamp_type = -1) for testing purpose. then fs2.kafka will not allow me to do that.

**Comment by vlovgr** [comment]
Right, so there's a choice between being 'correct but not isomorphic to the Java `ConsumerRecord`', or 'incorrect but isomorphic to the Java `ConsumerRecord`'.  If this is only for testing purposes, can't you change to only test with/generate valid instances? (Not ideal, but circumvents the issue.)

If not, then we might have to resort to introducing a `Timestamp.unknown` or similar for this case.

**Comment by chenharryhua** [comment]
My humble option is that if fs2.kafka treat java ConsumerRecord as payload, then isomorphic to the original form is necessary. if fs2.kafka depends on those field to do some computation, then it's OK to modify them. even though I still feel uncertain that as a middle ware, is it good to change it?

**Comment by vlovgr** [comment]
@chenharryhua Feel free to pull request `Timestamp.unknown`.

**Comment by chenharryhua** [comment]
@vlovgr Thanks. I will think about how Timestamp.unknown looks like and its relationship with Timestamp.none.

**Comment by chenharryhua** [comment]
Great! thanks @vlovgr I am looking forward to the next release. please free free to close the ticket.

**Comment by vlovgr** [comment]
Thanks again @chenharryhua! I'll get a new release out later today.

Fixed by #213.
