### ISSUE TITLE
How to close an active consumer?

### ISSUE THREAD

**Issue by bifunctor** [ovotech/fs2-kafka#222]
Hi all

First of all, I would like to say thanks your guys for the wonderful library. 

Now to the question. Is there a way, to close an active consumer?

https://static.javadoc.io/org.apache.kafka/kafka-clients/2.1.0/org/apache/kafka/clients/consumer/KafkaConsumer.html#close--

Thanks

**Comment by vlovgr** [comment]
This is handled automatically, but if you would like to force a `close`, you can use [`fiber.cancel`](https://ovotech.github.io/fs2-kafka/api/fs2/kafka/KafkaConsumer.html#fiber:cats.effect.Fiber[F,Unit]) on the `KafkaConsumer`. This will also interrupt streams from `stream` and `partitionedStream`.

**Comment by bifunctor** [comment]
Awesome. thanks a lot
