### ISSUE TITLE
KafkaProducer does not produce record

### ISSUE THREAD

**Issue by bifunctor** [ovotech/fs2-kafka#231]
Hi all 
I have the problem, that the KafkaProducer does not send the record to Kafka. 
The code is host on https://gitlab.com/sweetsoft/connector/blob/master/consumer/src/test/scala/com/sweetsoft/consumer/MaintainerSpec.scala and the problem is: 

```scala
private def sendRecord[F[_]](msg: Envelop, settings: ProducerSettings[F, String, String])
                              (implicit F: ConcurrentEffect[F], context: ContextShift[F])
  : Stream[F, Unit] =
    Stream.eval(Applicative[F].pure(ProducerRecords.one[String, String](ProducerRecord(msg.topic, msg.event, msg.data))))
      .through(produce[F, String, String, Unit](settings))
      .map { e =>
        println(e)
        ()
      }

```
It does not send the record to Kafka. 

You can download the code and test it.  
Thanks for your help.

**Comment by vlovgr** [comment]
It looks like you've forgotten to compile the `Stream` and run the effect (e.g. `.compile.drain.unsafeRunSync`).

**Comment by bifunctor** [comment]
I would say, I've called it and it is here:
```
        consumer
          .flatMap(res => record.map(_ => res))
          .map { res =>
            res.status should be(200)
          }.compile.drain
```
I delay the call.

**Comment by vlovgr** [comment]
Right, but you also need `unsafeRunSync` for it to actually run.

**Comment by bifunctor** [comment]
And the run happen here:
```
  private def startEndpoint(mock: ServiceDiscovery[Id], admin: KafkaAdminClient[IO],
                            testCode: Helpers[IO, Id] => IO[Unit])
  : IO[Unit] = {
    BlazeClientBuilder[IO](global).resource.use { client =>
      MockEndpointServer(mock)
        .start
        .flatMap(f => IO.sleep(2.second).map(_ => f))
        .flatMap(f => testCode(Helpers(client, admin, mock)).map(_ => f))
        .unsafeRunSync()
        .cancel
    }
  }
```
Or do I have to call `unsafeRunSync` twice?

**Comment by vlovgr** [comment]
You should ideally only have one `unsafeRunSync` at the very end of the test, which looks to be at the end of `process`. It looks like the `process` function currently discards the effect without running it.
