### ISSUE TITLE
Possibly leaking org.apache.kafka.clients.consumer.KafkaConsumer instance

### ISSUE THREAD

**Issue by retriku** [ovotech/fs2-kafka#232]
When checking fs2-kafka stream behavior during errors, I noticed  following warning in logs

`2019-10-08 23:25:58,472 | WARN | o.a.kafka.common.utils.AppInfoParser - Error registering AppInfo mbean
javax.management.InstanceAlreadyExistsException: kafka.consumer:type=app-info,id=client_id
	at java.management/com.sun.jmx.mbeanserver.Repository.addMBean(Repository.java:436)`

I managed to reproduce error in following test case (I ran it from `KafkaConsumerSpec`):
```
it("should restart properly on error") {
      withKafka { (config, topic) =>
        createCustomTopic(topic, partitions = 3)
        val produced = (0 until 1).map(n => s"key-$n" -> s"value->$n")
        publishToKafka(topic, produced)

        val conf = consumerSettings[IO](config)

        consumerStream[IO]
          .using(conf.withClientId("client_id"))
          .evalTap(_.subscribeTo(topic))
          .flatMap(_.stream)
          .flatMap(Stream.emit(_) >> Stream.raiseError[IO](new RuntimeException))
          .attempts(Stream.emit(1.second))
          .compile
          .toVector
          .unsafeRunSync
      }
    }
```
Enable logging and check logs. Notice that I have changed `client.id` property to a specific value. Also I checked out code tagged with "v0.20.1".

Setup:
Java: 11.0.4
Scala: 2.12.8
sbt:1.3.0
fs2-kafka: 0.20.1
cats: 2.0.0
cats-effect: 2.0.0

Let me know if you need more info.

**Comment by retriku** [comment]
I have created a small sample project https://github.com/retriku/fs2-kafka-consumer. Follow instructions from README.md in order to reproduce issue

**Comment by marcodippy** [comment]
@retriku I think this could do the trick:

```scala
consumerStream[IO]
          .using(conf.withClientId("client_id"))
          .evalTap(_.subscribeTo(topic))
          .flatMap(_.stream)
          .flatMap(Stream.emit(_) >> Stream.raiseError[IO](new RuntimeException))
          .scope  // <--- this should guarantee that the current consumer resource is actually released  
          .attempts(Stream.emit(1.second))
          .compile
          .toVector
          .unsafeRunSync
```

this should explain why :) https://gitter.im/functional-streams-for-scala/fs2?at=5ce5088decdf942b4c25877e

**Comment by retriku** [comment]
Thanks a lot @marcodippy! Looks like it really solves the problem.

Closing this ticket

**Comment by marcodippy** [comment]
As far as I understand there's recently been a change in the behaviour of scopes (https://github.com/functional-streams-for-scala/fs2/pull/1574); I'm no expert, but it looks like in the latest version we shouldn't need to call `.scope` explicitly there anymore, but I tried that on fs2 `2.0.1` and it still doesn't work as we'd expect. I'll ask the fs2 folks :)
