### ISSUE TITLE
Support ACL management in KafkaAdminClient

### ISSUE THREAD

**Issue by novakov-alexey** [ovotech/fs2-kafka#250]
Add support of Java AdminClient methods such as 
- describeAcls
- createAcls
- deleteAcls

@vlovgr appreciate your input on this issue. As I see, the KafkaAdminClient.scala just needs to be extended with above operations.

**Comment by vlovgr** [comment]
> As I see, the KafkaAdminClient.scala just needs to be extended with above operations.

Yes, that's right. :)
