### ISSUE TITLE
Question: equivalent implementation of Synchronized class?

### ISSUE THREAD

**Issue by chenharryhua** [ovotech/fs2-kafka#256]
I am studying the implementation of Synchronized class in fs2-kafka: https://github.com/ovotech/fs2-kafka/blob/master/modules/core/src/main/scala/fs2/kafka/internal/Synchronized.scala#L43

I come up with an alternative but I am not quite sure if it is equivalent to fs2-kafka:
``` 
def of[F[_], A](a: A)(implicit F: Concurrent[F]): F[Synchronized[F, A]] =
    MVar[F].of[A](a).map(mv =>
        new Synchronized[F, A] {
          override def use[B](f: A => F[B]): F[B] = F.bracket(mv.take)(f)(v => mv.put(v))
        })
```
in case it is equivalent, what's the benefit of using Deferred + Ref? 
thanks a lot.

**Comment by vlovgr** [comment]
We used `MVar` briefly in #5 and replaced it with `Synchronized` in #6. I believe the benefit is small for fs2-kafka's use case in particular. However, `Synchronized` is a more simple construct than `MVar` (fewer possible states), and `Synchronized` avoids this issue: https://github.com/typelevel/cats-effect/issues/382#issuecomment-433739248.

I'm closing this, but feel free to ask further questions. :)
