### ISSUE TITLE
Publish to Maven Central.

### ISSUE THREAD

**Issue by zarthross** [ovotech/fs2-kafka#39]
Anyway we can get this library published to Maven Central?

**Comment by smourapina** [comment]
I was trying to add this library to my project and ran into a problem (error when compiling with the mill build tool):

```
1 targets failed
consumer.compileClasspath 
Resolution failed for 1 modules:
--------------------------------------------
  com.ovoenergy:fs2-kafka_2.12:0.16.4 
	not found: /Users/<MyUser>/.ivy2/local/com.ovoenergy/fs2-kafka_2.12/0.16.4/ivys/ivy.xml
	not found: https://repo1.maven.org/maven2/com/ovoenergy/fs2-kafka_2.12/0.16.4/fs2-kafka_2.12-0.16.4.pom
	not found: https://oss.sonatype.org/content/repositories/releases/com/ovoenergy/fs2-kafka_2.12/0.16.4/fs2-kafka_2.12-0.16.4.pom
	not found: https://oss.sonatype.org/content/repositories/snapshots/com/ovoenergy/fs2-kafka_2.12/0.16.4/fs2-kafka_2.12-0.16.4.pom
	checksum format error: /Users/<MyUser>/Library/Caches/Coursier/v1/https/bintray.com/ovotech/maven/com/ovoenergy/fs2-kafka_2.12/0.16.4/fs2-kafka_2.12-0.16.4.pom.sha1
```

According to the sbt documentation (https://www.scala-sbt.org/1.x/docs/Faq.html): "This error occurs when the published checksum, such as a sha1 or md5 hash, differs from the checksum computed for a downloaded artifact, such as a jar or pom.xml."

So, I would second either publishing to Maven Central or fixing the published checksum.

**Comment by vlovgr** [comment]
@smourapina I'm not sure where that file, `fs2-kafka_2.12-0.16.4.pom.sha1` is coming from, because there is no such file published, as far as I can tell. All the current checksums are MD5, like e.g. `fs2-kafka_2.12-0.16.4.pom.md5`. You should be able to see all published files here: https://bintray.com/ovotech/maven/fs2-kafka/0.16.4

Regarding Maven Central, I'm just waiting for Sonatype to grant permissions, and then next release forwards will be on Maven Central rather than Bintray.

**Comment by smourapina** [comment]
@vlovgr Thanks for the quick reply. Unfortunately at the moment there does not seem to be a workaround for this issue with `mill`, and I am not sure either where the file is coming from.

Do you have an estimate as to when you will be able to publish to Maven Central?

**Comment by vlovgr** [comment]
@smourapina Have you tried clearing the Coursier cache, as in having this directory deleted?

```
/Users/<MyUser>/Library/Caches/Coursier/v1/https/bintray.com/ovotech/maven/com/ovoenergy/fs2-kafka_2.12/0.16.4/
```

It's all up to Sonatype at this point. From past experience, I would guess a couple of days, but there's no real estimate, unfortunately.

**Comment by smourapina** [comment]
@vlovgr Yes, I have tried that already. Same result. Thanks!

**Comment by vlovgr** [comment]
0.17.0 is out on Maven Central now.

Release notes are here:
https://github.com/ovotech/fs2-kafka/releases/tag/v0.17.0
