### ISSUE TITLE
Kafka log messages duplicated

### ISSUE THREAD

**Issue by countfloyd** [ovotech/fs2-kafka#75]
More of a question than an issue. Sorry, not sure where else to ask. 

I have a program using fs2-kafka that works fine but all of the Kafka driver messages are duplicated. Is this normal?

12:03:10.606 [scala-execution-context-global-31] INFO  o.a.k.c.s.a.AbstractLogin - Successfully logged in.
12:03:10.606 [scala-execution-context-global-31] INFO  o.a.k.c.s.a.AbstractLogin - Successfully logged in.
12:03:10.644 [scala-execution-context-global-31] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka version : 2.1.0
12:03:10.644 [scala-execution-context-global-31] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka version : 2.1.0
12:03:10.644 [scala-execution-context-global-31] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId : eec43959745f444f
12:03:10.644 [scala-execution-context-global-31] INFO  o.a.kafka.common.utils.AppInfoParser - Kafka commitId : eec43959745f444f
12:03:11.033 [fs2-kafka-consumer-37] INFO  org.apache.kafka.clients.Metadata - Cluster ID: eZRQO2AEQK-BYCMvtH1GCA
12:03:11.033 [fs2-kafka-consumer-37] INFO  org.apache.kafka.clients.Metadata - Cluster ID: eZRQO2AEQK-BYCMvtH1GCA
12:03:11.034 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Discovered group coordinator kafka:9093 (id: 2147482646 rack: null)
12:03:11.034 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Discovered group coordinator kafka:9093 (id: 2147482646 rack: null)
12:03:11.036 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Revoking previously assigned partitions []
12:03:11.036 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Revoking previously assigned partitions []
12:03:11.036 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] (Re-)joining group
12:03:11.036 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] (Re-)joining group
12:03:11.079 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Successfully joined group with generation 11
12:03:11.079 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.AbstractCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Successfully joined group with generation 11
12:03:11.080 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Setting newly assigned partitions [ebx-templates-0, ebx-users-0, ebx-contracts-0]
12:03:11.080 [fs2-kafka-consumer-37] INFO  o.a.k.c.c.i.ConsumerCoordinator - [Consumer clientId=ebx-plugin-test-1.0, groupId=ebx-plugin-test-1.0] Setting newly assigned partitions [ebx-templates-0, ebx-users-0, ebx-contracts-0]

**Comment by vlovgr** [comment]
Hi @countfloyd! This is not an issue with fs2-kafka, but how your logging has (or has not) been setup. These log entries come from the Java Kafka library, and you should setup a logging framework, e.g. [Logback](https://logback.qos.ch/). You can find a simple Logback configuration in [`logback-test.xml`](https://github.com/ovotech/fs2-kafka/blob/master/src/test/resources/logback-test.xml). If you change the log level on [this line](https://github.com/ovotech/fs2-kafka/blob/master/src/test/resources/logback-test.xml#L9) to e.g. `INFO`:

```xml
<root level="INFO" additivity="false">
```

and run `sbt test` for the project, you should not see duplicated log messages.

**Comment by countfloyd** [comment]
Great! Works like a charm. Thanks so much for the help.
