### ISSUE TITLE
Microlibrary for Synchronized

### ISSUE THREAD

**Issue by ChristopherDavenport** [ovotech/fs2-kafka#77]
Hi all! I was looking to create a microlibrary exposing your internal synchronized construction. 

https://github.com/ovotech/fs2-kafka/blob/master/src/main/scala/fs2/kafka/internal/Synchronized.scala

All licenses will be respected, and developer credits given.

Is that alright with you? I think it would be very useful for many constructs.

**Comment by SystemFw** [comment]
Chris already mentioned it to me, we wanted to double check it was ok with you  as well :)
