### ISSUE TITLE
Better document the backpressure and `pollInterval`

### ISSUE THREAD

**Issue by backuitist** [ovotech/fs2-kafka#82]
The documentation says that the (consumer) stream is backpressured. But after a quick look at the code base I cannot easily find such evidence. This makes it hard to set the `pollInterval` setting.

As far as I understand there are 3 pieces at work in the consumer stream:
1. the poll loop -- responsible for throttling the poll requests (the poll queue is bounded with 1 element)
2. the consumer loop (`KafkaConsumerActor`) -- handles both fetch requests issued by the stream as well as poll requests by the poll loop, using a `State` variable that accumulates fetch requests along with fetched kafka records.
3. the stream -- emits fetch requests on-demand (pull based)

At first it seems that the consumer loop simply accumulates endlessly records in the `State.records`. But then I came across the poll function in the consumer loop:
```scala
val resume = (requested intersect assigned) diff available
val pause = assigned diff resume

consumer.pause(pause.asJava)
consumer.resume(resume.asJava)
```
This seems like unless a fetch request is present no polling will be performed, in effect providing backpressure?

Perhaps some high-level documentation of the code-base would be useful?

My understanding is that `pollInterval` is only there to reduce the pressure on Kafka, if the record consumption rate (the logic that consumes the stream) exceeds the production rate (the kafka producer, up-stream)?

**Comment by vlovgr** [comment]
Hi @backuitist! Thanks for raising this question.

The backpressure actually happens in the stream using the following queue.

https://github.com/ovotech/fs2-kafka/blob/cf301e9f67018361fdb39698ce9bb4d7fefbbccf/src/main/scala/fs2/kafka/KafkaConsumer.scala#L306-L307

Essentially, we are trying to fetch records on every assigned partition in parallel, while only using a single consumer instance. If the processing of those records is slow, the queues will fill up, and we won't be fetching more records until the queues become empty. There is a case to make the size of the queues configurable, but it has not been asked for or implemented yet.

The `pollInterval` controls how often the Java `KafkaConsumer` is allowed to run. The Java consumer  uses blocking, and requires a poll loop. The [documentation](https://kafka.apache.org/21/javadoc/?org/apache/kafka/clients/consumer/KafkaConsumer.html) goes into great detail about how this works. As you've noted, we only ask for records on partitions where there is downstream demand.

**Comment by vlovgr** [comment]
@backuitist I've opened #83 to address this issue.

**Comment by backuitist** [comment]
Hi, thanks for addressing this!
Wouldn't you say that https://github.com/ovotech/fs2-kafka/blob/cf301e9f67018361fdb39698ce9bb4d7fefbbccf/src/main/scala/fs2/kafka/internal/KafkaConsumerActor.scala#L351
is also responsible for the backpressure?
Without the `pause`, the "actor" would endlessly fill-up the `State.records`? To me that's the non-trivial part in understanding how the `pollInterval` works. Otherwise you might end-up thinking that the consumer polls no matter what, independently from downstream, therefore having to set the `pollInterval` carefully as it could lead to a memory leak (polling faster than downstream can consume).
Maybe this could be explained in the README?

**Comment by vlovgr** [comment]
Thanks for your further clarifications, @backuitist!

There are two different perspectives when it comes to documenting backpressure.

- As a user of the library, you mainly want to know that it exists, and how you can control it. #83 addresses this with the `maxPrefetchBatches` setting along with an explanation of how it works.
- As a contributor, you mainly want to know how it's implemented. I've added a short explanation to the `KafkaConsumerActor` scaladoc in #83, explaining the behaviour you're describing.

I believe there's also room for more high-level documentation. The current documentation is pretty minimal, and needs expanding. When I get around to it, I'll definitely try to incorporate a more thorough explanation of how backpressure is implemented.
