### ISSUE TITLE
Kafka.Id is private

### ISSUE THREAD

**Issue by chenharryhua** [ovotech/fs2-kafka#86]
I failed to annotate the return type because Kafka.Id is private.

` val k: ProducerMessage[kafka.Id, K, V, Unit]  ` //compiler error: Symbol Id is inaccessible from this place
would it be better to use cats.Id instead?

**Comment by vlovgr** [comment]
Thanks for raising this @chenharryhua!

We cannot use `cats.Id` because the type parameter is invariant, while we need it to be covariant (`type Id[+A] = A`). I've raised #87 to make `fs2.kafka.Id` public, but in the meantime you can  define it yourself if you want to.

**Comment by chenharryhua** [comment]
Thanks. I am waiting for next release. Let intellij complain for a while. :)
