### ISSUE TITLE
Support for producing unkeyed messages

### ISSUE THREAD

**Issue by ranjanibrickx** [ovotech/fs2-kafka#96]
Hello,

First of all, thank you for the https://github.com/ovotech/fs2-kafka-client as well as https://github.com/ovotech/fs2-kafka libraries! 

I was looking at switching to the latest kafka version, and was looking to move to this (`fs2-kafka`) library. One question I had was if there is any plan to support unkeyed records in this library?

**Comment by vlovgr** [comment]
Thanks for raising this issue @ranjanibrickx!

> [...] any plan to support unkeyed records in this library?

What kind of support are you looking for? If all records are unkeyed, you can easily define the serializer and deserializer as follows, and use them as the `keySerializer` and `keyDeserializer` when creating `ProducerSettings` and `ConsumerSettings`, respectively. Simply provide the unit value `()` as key when serializing records. (We could add these to the library as `Serializer.unit` and `Deserializer.unit`.)

```scala
Serializer.const[Unit](null)
Deserializer.const[Unit](())
```

If you have a mix of unkeyed and keyed records, and want the keys when available, we could add a `Deserializer#option` function which gives you `None` for unkeyed records, so you could do something like `Deserializer[String].option`.

**Comment by vlovgr** [comment]
@ranjanibrickx I've opened #97 to include the mentioned additions, and some more. The pull request contains further explanations. Is there any anything else you're missing?

**Comment by ranjanibrickx** [comment]
Thanks a lot for the quick and helpful response! For the moment, we have all messages on a topic as unkeyed records, so what you proposed as the first option works perfectly --  I had missed that when I was exploring yesterday! But thank you for creating the PR to introduce the support for a mix of unkeyed and keyed messages too!

**Comment by vlovgr** [comment]
@ranjanibrickx The changes in #97 are included in the 0.19.4 release.
